envs:
  - name: MemoryBins
    n_envs: 1000
    data_source: memory_bins
    seed: [1, 1000, 1]
    max_turns: 60
    response_length_per_turn: 512
    config:
      n_bins: 5
      n_instructions: 3
      max_steps: 60
      bin_layout: fixed
      cell_size: 64
